// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCloueTshHxyurMlF6lLYn4dBDEjgvnlaU',
    appId: '1:439110786341:web:8fc87c240d057e6357cecc',
    messagingSenderId: '439110786341',
    projectId: 'chat-app-3bcf7',
    authDomain: 'chat-app-3bcf7.firebaseapp.com',
    storageBucket: 'chat-app-3bcf7.appspot.com',
    measurementId: 'G-0YNGKXMHES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjv-8wR1WuWQ3rUnhAvGoJ39Z0PX9OLG8',
    appId: '1:439110786341:android:0bac916013c89eb557cecc',
    messagingSenderId: '439110786341',
    projectId: 'chat-app-3bcf7',
    storageBucket: 'chat-app-3bcf7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ3VADTqvNEMV7-BGoKDNp9jzjtyyNYq0',
    appId: '1:439110786341:ios:5a63a254d7b8d89f57cecc',
    messagingSenderId: '439110786341',
    projectId: 'chat-app-3bcf7',
    storageBucket: 'chat-app-3bcf7.appspot.com',
    iosBundleId: 'com.example.scholarchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ3VADTqvNEMV7-BGoKDNp9jzjtyyNYq0',
    appId: '1:439110786341:ios:5a63a254d7b8d89f57cecc',
    messagingSenderId: '439110786341',
    projectId: 'chat-app-3bcf7',
    storageBucket: 'chat-app-3bcf7.appspot.com',
    iosBundleId: 'com.example.scholarchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCloueTshHxyurMlF6lLYn4dBDEjgvnlaU',
    appId: '1:439110786341:web:d6b4cb2c7bd5ecfb57cecc',
    messagingSenderId: '439110786341',
    projectId: 'chat-app-3bcf7',
    authDomain: 'chat-app-3bcf7.firebaseapp.com',
    storageBucket: 'chat-app-3bcf7.appspot.com',
    measurementId: 'G-TH6M14S023',
  );
}
